console.log("\n");
console.log("HELLO WORLD!  HELLO WORLD!  HELLO WORLD!  HELLO WORLD!  HELLO WORLD!");
console.log("\n");
console.log("  XXXXXXXX     XXXXXX     XX      XX   XX   XXXXXXXX       XXXXXXXX");
console.log("XX           XX      XX   XX      XX   XX   XX      XX   XX");
console.log("XX           XX      XX   XX      XX   XX   XX      XX   XX");
console.log("XXXXXXX      XX      XX   XX      XX   XX   XXXXXXXX     XXXXXXX");
console.log("XX           XX      XX   XX      XX   XX   XX           XX");
console.log("XX           XX      XX   XX      XX   XX   XX           XX");
console.log("  XXXXXXXX     XXXXXXXX     XXXXXX     XX   XX             XXXXXXXX");
console.log("                      XX");
console.log("\n");
console.log("XXXXXXXX       XXXXXX     XXXXXXXX     XXXXXXXX       XXXXXXXX   XXXXXXXX");
console.log("XX      XX   XX      XX   XX      XX   XX      XX   XX           XX      XX");
console.log("XX      XX   XX      XX   XX      XX   XX      XX   XX           XX      XX");
console.log("XXXXXXXX     XXXXXXXXXX   XXXXXXXX     XX      XX   XXXXXXX      XXXXXXXX");
console.log("XX      XX   XX      XX   XX      XX   XX      XX   XX           XX      XX");
console.log("XX      XX   XX      XX   XX      XX   XX      XX   XX           XX      XX");
console.log("XX      XX   XX      XX   XX      XX   XXXXXXXX       XXXXXXXX   XX      XX");
console.log("\n");
console.log("HELLO WORLD!  HELLO WORLD!  HELLO WORLD!  HELLO WORLD!  HELLO WORLD!!");
console.log("\n");
console.log("GREATINGS FROM RARDER TEAM!");
